<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'Report' }}</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            color: #1f2937;
            font-size: 12px;
            margin: 24px;
        }

        .header {
            border-bottom: 2px solid #2563eb;
            padding-bottom: 12px;
            margin-bottom: 18px;
        }

        .title {
            font-size: 22px;
            font-weight: bold;
            color: #111827;
            margin: 0;
        }

        .subtitle {
            margin-top: 6px;
            color: #475569;
        }

        .meta {
            margin-top: 12px;
            font-size: 11px;
            color: #6b7280;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 18px;
            font-size: 11px;
        }

        th {
            background: #eff6ff;
            color: #1d4ed8;
            text-align: left;
            padding: 10px;
            border-bottom: 1px solid #bfdbfe;
        }

        td {
            padding: 10px;
            border-bottom: 1px solid #e2e8f0;
            vertical-align: top;
        }

        .muted {
            color: #6b7280;
        }

        .footer {
            margin-top: 24px;
            font-size: 10px;
            color: #6b7280;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $title ?? 'Report' }}</div>
        <div class="subtitle">{{ $subtitle ?? 'Generated report' }}</div>
        <div class="meta">
            Generated: {{ $generatedAt ?? now()->format('Y-m-d H:i:s') }}
            @if (!empty($dateRange))
                | Range: {{ $dateRange }}
            @endif
        </div>
    </div>

    @if (!empty($rows) && count($rows) > 0)
        <table>
            <thead>
                <tr>
                    @foreach ($columns as $column)
                        <th>{{ $column }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($rows as $row)
                    <tr>
                        @foreach ($row as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="muted">No report data available for the selected filters.</div>
    @endif

    <div class="footer">
        TIPIGANAN report generated by the system.
    </div>
</body>
</html>
